'''Language Dictionaries'''

import pandas as pd

 ##
class Language_Dictionary:

  def __init__(self,currency_var):
    self.currency_var=currency_var
#-----------------------------------------German Dictionary-----------------------


    self.lang_deu={'Main_File_vars': {'data_prep_succ': ('Datenaufbereitung abgeschlossen',
     'Die Daten werden nun visualisiert. Bitte haben Sie einen Moment Geduld!'),
    'data_prep_err': ('Datenaufbereitung abgebrochen',
     'Der Excelexport konnte nicht abgeschlossen werden (Err04). Das Programm wird geschlossen.'),
    'data_vis_succ': ('Datenvisualisierung erfolgreich abgeschlossen',
     'Die Ergebnisse wurden unter folgendem Ordner abgelegt:\n\n{self.accounts_data.res_dir}\n\nDas Programm wird jetzt geschlossen.'),
    'data_vis_err5': ('Datenvisualisierung abgebrochen',
     'Die Diagrammvorverarbeitung konnte nicht abgeschlossen werden (Err05). Das Programm wird jetzt geschlossen.'),
    'data_vis_err6': ('Datenvisualisierung abgebrochen',
     'Diagramme konnten nicht erstellt werden (Err06). Das Programm wird jetzt geschlossen.')},
   'GUI_Final_vars': {'mainwin_choice1': ('Csv-Daten analysieren', ''),
    'mainwin_choice2': ('Excel-Daten analysieren', ''),
    'mainwin_choice3': ('Urlaube separat auswerten', ''),
    'mainwin_choice4': ('Sparcents ausgeben', ''),
    'mainwin_choice5': ('Daten zusammenfügen', ''),
    'mainwin_choice6': ('Csv-Daten mit bestehenden Excel-Dateien verknüpfen (Langzeitanalyse)',
     ''),
    'mainwin_choice7': ('Haushaltsbuch mit Bargeldzahlungen in die Datenanalyse einbeziehen',
     ''),
    'mainwin_separator_text': ('<big>Weitere Analyse-Optionen</big>', ''),
    'mainwin_btn1': ('Rohdaten auswählen', ''),
    'mainwin_btn2': ('Auswertung starten', ''),
    'mainwin_xlsxinfo': ('Bitte beachten', 'Excel-Dateien'),
    'mainwin_donatinfo': ('Gefällt Ihnen KYSA?',
     'KYSA ist als Open-Source-Projekt auf Ihre Unterstützung angewiesen. Für weitere Informationen drücken Sie bitte OK. Vielen Dank!'),
    'aboutwin_linktext': ('KYSA Webseite', ''),
    'aboutwin_title': ('Über KYSA', ''),
    'donatewin_header':('Unterstützen',''),
    'donatewin_title': ('<big>Spenden für KYSA</big>', ''),
    'donatewin_text': ('KYSA ist ein Open-Source-Projekt und soll es auch bleiben.\nAuch wenn es nicht so wirkt, ist auch die Entwicklung einer kleinen Software sehr zeitaufwändig  und trotz der Verwendung von anderen Open-Source-Programmbibliotheken dennoch mit Kosten verbunden.\n\nWenn Ihnen KYSA gefällt und hilft, unterstützen Sie mich gerne mit einer kleinen Spende.  Ich freue mich auch über kleine Spenden, um dieses Programmprojekt weiter zu verbessern.  Als Dienstleister für Spenden (auch für meinen Blog) nutze ich die Open-Source-Spendenplattform Liberapay.  Alles weitere zum Spendenprozess findet sich auf der verlinkten Webseite: ',''),
    'donatewin_link': ('https://de.liberapay.com/Waldbader/donate','Spenden über Liberapay'),
    'setuiwin_header':('Einstellungen Benutzeroberfläche',''),
    'setuiwin_title':('<big>Einstellungen für Benutzeroberfläche</big>',''),
    'setuiwin_choicelabel':('<b>Anzeigesprache</b>','<b>Währungssymbol</b>'),
    'setuiwin_currencies1':('Euro (€)','Dollar ($)'),
    'setuiwin_currencies2':('Pfund (£)','Krone (Kr)'),
    'setuiwin_btn':('Einstellungen speichern',''),
    'setuiwin_nochoice':('Keine Änderungen vorgenommen','Sie können die Datenanalyse mit den bestätigten Voreinstellungen ohne Programmneustart beginnen.'),
    'setuiwin_newchoice':('Bitte beachten:','Die gewählten Einstellungen werden erst mit einem Programmneustart wirksam. Klicken Sie "OK" um das Programm jetzt zu schließen.'),
    'concatwin_header':('Daten-Zusammenführung',''),
    'concatwin_btn1': ('Abbrechen', ''),
    'concatwin_btn2': ('Weiter', ''),
    'concatwin_entryname': ('<b>Name für Datei {(colid+1)}:</b>', ''),
    'concatwin_choicename': ('Datei {colid+1}', ''),
    'concatwin_errselect': ('Unvollständige Eingabe',
     'Bitte wählen Sie mindestens 2 Dateien aus\noder brechen diesen Schritt ab!'),
    'concatwin_errnoname': ('Unvollständige Eingabe',
     'Sie haben für Ihre Auswahl keinen Namen eingegeben!'),
    'concatwin_errname': ('Fehlerhafte Eingabe',
     'Sie haben einen Namen eingegeben'),
    'concatwin_succ': ('Erfolgreiche Verknüpfungsauwahl!', ''),
    'prgrsswin_header': ('Datenaufbereitung läuft', ''),
    'prgrsswin_visualinfo': ('Datenvisualisierung läuft', '')},
   'Main_Func_vars': {'filechooser_csv': ('Csv-Dateien auswählen', ''),
    'filechooser_xlsx': ('Excel-Dateien auswählen', ''),
    'filechooser_longterm': ('Excel-Dateien für Verknüfung mit csv-Dateien auswählen',
     ''),
    'filechooser_cashbook': ('Haushaltsbuch-Excel-Datei auswählen', ''),
    'filechooser_classdir': ('Ordner mit Zuordnungstabelle auswählen', ''),
    'filechooser_resdir': ('Ablageordner für Ergebnisse auswählen', ''),
    'filechooser_filter1': ('CSV Dateien', ''),
    'filechooser_filter2': ('Excel Dateien', ''),
    'filechooser_filter3': ('Alle Dateien', ''),
    'start_analysis_err1': ('Fehlende Rohdaten',
     'Bitte wählen Sie mindestens eine Datei aus!'),
    'start_analysis_err2': ('Unplausible Auswahl',
     'Es wurde nur eine Datei eingegeben'),
    'importcheck_err': ('Fehler beim Datenimport!',
     'Es konnte keine der ausgewählten Dateien verarbeitet werden!\n\nWählen Sie neue Dateien!\n\nFehlercode(s):\n\n({errorcodes})'),
    'importcheck_succall': ('Datenimport abgeschlossen!',
     'Alle Dateien wurden erfolgreich importiert!'),
    'importcheck_succpart': ('Datenimport abgeschlossen!',
     'Es wurde:\n\n{successlisttext}\n\nerfolgreich eingelesen.\n\n\nFolgende Dateien konnten nicht verarbeitet werden:\n\n{errorlisttext}'),
    'etraimport_longterm': ('Zusätzliche Excel-Dateien einlesen',
     'Bitte wählen Sie im folgenden Schritt die Excel-Dateien für die Zusammenführung mit den csv-Daten aus oder brechen ab.'),
    'etraimport_cashbook': ('Haushaltsbuch einlesen',
     'Bitte wählen Sie im folgenden Schritt die Excel-Datei mit den Bargeldzahlungen aus oder brechen ab.'),
    'cashbookinfo_nodata': ('Keine Verknüpfung erfolgt',
     'Es wurden für die importierten Rohdaten keine korrespondierenden Daten im Haushaltsbuch gefunden.'),
    'cashbookinfo_err': ('Verknüpfung fehlgeschlagen',
     'Es konnten keine Daten aus dem Haushaltsbuch verknüpft werden.\nFolgende Codes weisen auf die Gründe hin:\n\n{errorlisttext}'),
    'cashbookinfo_succ': ('Verknüpfung erfolgreich!',
     'Zu folgenden importierten Rohdateien konnten passende Daten aus dem Haushaltsbuch hinzugefügt werden:\n\n{successlisttext}'),
    'cashbookinfo_succpart': ('Verknüpfung teilweise erfolgreich!',
     'Die Verknüpfung von Daten aus dem Haushaltsbuch war für folgende Rohdateien erfolgreich:\n\n{successlisttext}!\n\n\nBei folgende Rohdateien schlug der Abgleich fehl:\n\n{errorlisttext}'),
    'classtableimport_notexist': ('Zuordnungstabelle nicht gefunden!',
     'Wählen Sie den neuen Ordner'),
    'classtableimport_succ': ('Zuordnungstabelle erfolgreich gespeichert!', ''),
    'classtableimport_err': ('Fehler beim Import',
     'Im gewählten Ordner wurde keine Zuordnungstabelle gefunden.'),
    'excludelist': ('Sparcents', 'Haushaltsbuch')},    
   'Classifier_vars':{'tablename': ('Zuordnungstabelle.xlsx', 'Kategorie'),
   'tablesheets': ('Girokonto', 'Kreditkarte'),
   'noncategory': ('Sonstiges', '')},
   'Data_Proc_vars': {'act_value': ('Kreditkartenumsatz', ''),
    'sheetname_rawdata': ('Rohdaten', ''),
    'cashbookvars_name': ('Haushaltsbuch', 'Bargeldzahlung'),
    'holidayvars_name': ('Urlaube', 'Urlaubsauswertung'),  
    'holiday_searchwords':('Urlaub|Ferien|Auszeit|Kurzurlaub|Reise|Trip',''),
    'dataname_savecent': ('Sparcents', ''),
    'result_pathvars': ('Ergebnisse_', '_Auswertung'),
    'balance_normal': ('Gesamtsaldo\nder Periode', ''),
    'balance_savecent': ('Gesamtsumme der\nSparcents', ''),
    'balance_cashbook': ('Summe der berücksichtigten Haushaltsbuchkosten in der Periode','Gesamtsumme der\nBargeldzahlungen'),
    'sheetname_basis': ('Aufbereitete Daten',["Buchungstag","Wertstellung (Valuta)","Vorgang","Buchungsinformationen","Umsatzbetrag ("+self.currency_var+")","Monat","Kategorie"]),
    'sheetname_catdata': ('Aufstellung Kategorien',["Kategorie","Kumulierte Absolutbeträge ("+self.currency_var+")","Durchschnittliche Absolutbeträge pro Monat ("+self.currency_var+")"]),
    'sheetnames_savecent1': ('Aufbereitete Daten',["Buchungstag","Wertstellung (Valuta)","Vorgang","Buchungsinformationen","Umsatzbetrag ("+self.currency_var+")","Monat","Kategorie","Sparcents ("+self.currency_var+")","Herkunft Sparcent"]),
    'sheetnames_savecent2': ('Monatliche Sparcents',["Monat","Sparcents ("+self.currency_var+")"]),
    'sheetnames_savecent3': ('Sparcents nach Konto-Herkunft',["Herkunft Sparcent","Kumulierte Sparcents ("+self.currency_var+")","Durchschnittliche Sparcents pro Monat ("+self.currency_var+")"]),
    'sheetnames_cashbook1': ('Aufbereitete Daten',["Buchungstag","Wertstellung (Valuta)", "Vorgang", "Buchungsinformationen", "Umsatzbetrag ("+self.currency_var+")","Monat","Kategorie", "Konto", "Bargeldbezeichnung"]),
    'sheetnames_cashbook2': ('Aufstellung Kategorien',["Kategorie","Kumulierte Absolutbeträge ("+self.currency_var+")","Durchschnittliche Absolutbeträge pro Monat ("+self.currency_var+")"]),
    'sheetnames_cashbook3': ('Aufstellung Bargeldherkunft',["Bezeichnung Bargeldherkunft","Kumulierte Absolutbeträge ("+self.currency_var+")","Durchschnittliche Absolutbeträge pro Monat ("+self.currency_var+")"])},
   'Plot_Proc_vars': {'costplot_search': ('Urlaub|Gesamtsaldo|Sonstiges|Abhebung|Bargeld',
     '',
     '',
     ''),
    'costplot_savecent': ('Sparcents','Übersicht über die Herkunft und Summe der "{element_name}"',
     'Übersicht Sparcents.png',''),
    'monthplot_savecent': ('Sparcents','Absteigend sortierte Aufstellung der "{element_name}" je Monat',
     'Monatliche Sparcents.png',''),
    'costplot_holiday_rename': ('Urlaube','Gesamtsaldo\nder Periode',
     'Summe aller\nUrlaubsausgaben',''),
    'costplot_holiday': ('Urlaube','Kostensummen der einzelnen Urlaube',
     'Übersicht Urlaubskosten.png',''),
    'monthplot_holiday': ('Urlaube','Monatliche Aufstellung der Urlaubsausgaben',
     'Monatsaufstellung Urlaube.png',''),
    'costplot_cashbook1': ('Haushaltsbuch','Übersicht über die Bargeldzahlungen nach Kostenkategorien',
     'Übersicht Bargeldzahlungen.png',''),
    'costplot_cashbook2': ('Haushaltsbuch','Übersicht über die Bargeldabhebungen nach Konto',
     'Übersicht Bargeldabhebungen.png',''),
    'monthplot_cashbook': ('Haushaltsbuch','Monatliche Aufstellung der Bargeldzahlungen',
     'Monatsaufstellung Bargeldzahlungen.png',''),
    'costplot_basis': ('Gesamtsaldo\nder Periode','Detaillierte Gesamtübersicht der Kostenkategorien für "{element_name}"',
     'Komplettübersicht Kostenkategorien.png',''),
    'monthplot_basis': ('Gesamtsaldo\nder Periode','Aufstellung der Monatssalden für "{element_name}"',
     'Monatsaufstellung.png',''),
    'overviewplot_adjustments1': ('Miete','Gesamtsaldo\nder Periode','Aktien-\ngeschäfte',
     'ETFS / Wert-\npapiersparen'),
    'overviewplot_adjustments2': ('Einkünfte inkl.\nInvestergebnis',
     'Restliche Kosten-\npositionen',
     '',
     ''),
    'overviewplot_plotinfo': ('Überblicksübersicht Kosten und Einkünfte für "{element_name}',
     'Einkünfte und TOP-Kostenblöcke',
     'Einkünfte inkl. Saldo Kapitalanlagen\n & Restliche Kostenpositionen',
     'Überblicksübersicht.png'),
    'piechart_2%name': ('Restliche mit <2,5%', '', '', ''),
    'holiday_adjust_words': ('Urlaub', 'Urlaube', 'Sparcents', 'Haushaltsbuch'),
    'holiday_adjust_costplot': ('Urlaube gesamt',
     'Übersicht der Kostenkategorien mit Urlauben (gesamt) für "{element_name}"',
     'Kostenübersicht Kosten_Urlaube (gesamt).png',
     ''),
    'holiday_adjust_piechart': ('Tortendiagramm Kostenkategorien >2,5% Anteil für "{element_name}"',
     'Anteilsübersicht mit Urlauben zusammengefasst',
     'Anteilsübersicht ohne Urlaube',
     'Tortendiagramm Kostenanteile_Urlaub.png'),
    'invest_adjust_words': ('Aktien-\ngeschäfte',
     'ETFS / Wert-\npapiersparen',
     '',
     ''),
    'invest_adjust_costplot': ('Detaillierte Übersicht Kostenkategorien mit Urlauben (gesamt) ohne Investkosten für "{element_name}"',
     'Kostenübersicht_ohne Invest.png',
     '',
     ''),
    'invest_adjust_piechart': ('Tortendiagramm Kostenkategorien >2,5% Anteil für "{element_name}"',
     'Anteilsübersicht mit Invest',
     'Anteilsübersicht ohne Invest',
     'Tortendiagramm Kostenanteile_Invest.png'),
    'income_adjust_words1': ('Urlaube', 'Sparcents', 'Haushaltsbuch', ''),
    'income_adjust_words2': ('Lohn', 'Gehalt', '', ''),
    'income_costplot': ('Detaillierte Übersicht über die verschiedenen Einkommensquellen für "{element_name}"',
     'Einkommensübersicht.png',
     '',
     ''),
    'income_piechart': ('Tortendiagramm Einkommensquellen >2,5% Anteil für "{element_name}"',
     'Anteilsübersicht mit Lohn / Gehalt',
     'Anteilsübersicht ohne Lohn / Gehalt',
     'Tortendiagramm Einkommensquellen.png'),
    'boxsplit_partname':(' Teil ','','',''),
    'boxplot_info': ('Boxplot aller Umsätze nach Kategorie für "{element_name}"',
     'Boxplot.png',
     '',
     ''),
    'vioplot_info': ('Violinplot aller Umsätze nach Kategorie für "{element_name}"',
     'Violinplot.png',
     '',
     '')},
   'Plotting_vars': {'axcatdata': ('Kategorie', ''),
   'timesep_month': ('bis',''),
    'box_violplot_xaxis': ('Einzelumsätze ('+self.currency_var+')', ''),
    'costplot_yaxes': ('Gesamtbeträge der Periode ('+self.currency_var+')', 'Durschschnittliche Monatsbeträge ('+self.currency_var+')'),
    'monthplot_extralabel': ('Ø-Monatssaldo des\n Gesamtzeitraums:\n', ''),
    'monthplot_axes': ('Saldo je Monat ('+self.currency_var+')','Monate')}}



#-----------------------------------------English Dictionary-----------------------

    self.lang_eng={'Main_File_vars': {'data_prep_succ': ('Data processing successful',
   'The data is now visualized. Please wait a moment!'),
  'data_prep_err': ('Data processing interrupted',
   'The Excelexport could not be completed (Err04). The program is closed.'),
  'data_vis_succ': ('Data visualization successful',
   'The results have been saved to the following folder:\n\n{self.accounts_data.res_dir}\n\n The program is now closed.'),
  'data_vis_err5': ('Data visualization interrupted',
   'The plotting preprocessing could not be completed (Err05). The program is now closed.'),
  'data_vis_err6': ('Data visualization interrupted',
   'Diagrams could not be created (Err06). The program is now closed.')},
 'GUI_Final_vars': {'mainwin_choice1': ('Analyse csv data', ''),
  'mainwin_choice2': ('Analyse Excel data', ''),
  'mainwin_choice3': ('Extract vacations to separate file', ''),
  'mainwin_choice4': ('Calculate Roundies', ''),
  'mainwin_choice5': ('Merge data', ''),
  'mainwin_choice6': ('Link csv data with existing Excel-results', ''),
  'mainwin_choice7': ('Use cashbook entries for analysis', ''),
  'mainwin_separator_text': ('<big>Additional options</big>', ''),
  'mainwin_btn1': ('Select raw data', ''),
  'mainwin_btn2': ('Run analysis', ''),
  'mainwin_xlsxinfo': ('Please note',
   "Excel files that are to be evaluated must have a 'Processed Data' worksheet in KYSA's own formatting. If you have not yet evaluated any data"),
  'mainwin_donatinfo': ('Do you like KYSA?', 'KYSA needs your help'),
  'aboutwin_linktext': ('KYSA website', ''),
  'aboutwin_title': ('About KYSA', ''),
  'donatewin_header': ('Support KYSA', ''),
  'donatewin_title': ('<big>Donate for KYSA</big>', ''),
  'donatewin_text': ("KYSA is an open source project and should remain so.\nEven if it doesn't seem like it, developing a small piece of software is very time-consuming and, despite the use of other open source program libraries, still involves costs.\n\n If you like KYSA and would like to help, please support me with a small donation. Even small amounts help me to further improve this programming project. I use the open source donation platform Liberapay as service provider. Everything else about the donation process can be found on the linked website:",
   ''),
  'donatewin_link': ('https://en.liberapay.com/Waldbader/donate','Donate via Liberapay'),
  'setuiwin_header': ('UI Settings', ''),
  'setuiwin_title': ('<big>Set User Interface (UI) preferences</big>', ''),
  'setuiwin_choicelabel':('<b>UI language</b>','<b>Currency sign</b>'),
  'setuiwin_currencies1':('Euro (€)','Dollar ($)'),
  'setuiwin_currencies2':('Pound (£)','Krone (Kr)'),
  'setuiwin_btn':('Save settings',''),
  'setuiwin_nochoice':('No changes made','You can start the data analysis with the preselected preferences without restarting the program.'),
  'setuiwin_newchoice':('Please note:','Your selection will only become effective after a program restart. Press "OK" to close the program now.'),
  'concatwin_header': ('Concat data', ''),
  'concatwin_btn1': ('Cancel', ''),
  'concatwin_btn2': ('Proceed', ''),
  'concatwin_entryname': ('<b>File name {(colid+1)}:</b>', ''),
  'concatwin_choicename': ('File {colid+1}', ''),
  'concatwin_errselect': ('iIncomplete input',
   'Please choose at least 2 files\nor skip this step'),
  'concatwin_errnoname': ('iIncomplete input',
   'You have not entered a name for your selection!'),
  'concatwin_errname': ('Incorrect input',
   'You have entered a name that is already taken!'),
  'concatwin_succ': ('Concatenation successful', ''),
  'prgrsswin_header': ('Processing Data', ''),
  'prgrsswin_visualinfo': ('Visualizing Data', '')},
 'Main_Func_vars': {'filechooser_csv': ('Choose csv files', ''),
  'filechooser_xlsx': ('Choose excel files', ''),
  'filechooser_longterm': ('Choose csv files for concatenation with csv files',
   ''),
  'filechooser_cashbook': ('Choose your cashbook', ''),
  'filechooser_classdir': ('Set folder holding classification table', ''),
  'filechooser_resdir': ('Set folder for results', ''),
  'filechooser_filter1': ('csv files', ''),
  'filechooser_filter2': ('excel files', ''),
  'filechooser_filter3': ('all files', ''),
  'start_analysis_err1': ('Missing data', 'Please choose at least one file'),
  'start_analysis_err2': ('Implausible selection',
   'You selected concatenation but only one file was chosen'),
  'importcheck_err': ('Import error',
   'None of the selected files could be processed!\n\nPlease select new files!\n\nerrorcode(s):\n\n({errorcodes})'),
  'importcheck_succall': ('Import finished',
   'All files were successfully imported'),
  'importcheck_succpart': ('Import finished',
   'The following files were processed successfully:\n\n{successlisttext}\n\n\n\n The following files could not be processed:\n\n{errorlisttext}'),
  'etraimport_longterm': ('Import additional Excel files',
   'Please select the Excel files for merging with the csv data in the following step or cancel.'),
  'etraimport_cashbook': ('Import cashbook',
   'Please select the Excel file with the cash payments in the following step or cancel.'),
  'cashbookinfo_nodata': ('No data linkage established',
   'For the imported raw data no corresponding data were found in the cashbook.'),
  'cashbookinfo_err': ('Data linkage error',
   'No data from the cashbook could be linked. \nThe following codes indicate the reasons:\n\n{errorlisttext}'),
  'cashbookinfo_succ': ('Data linkage successful',
   'To the following imported raw files matching data from the cashbook could be added:\n\n{successlisttext}'),
  'cashbookinfo_succpart': ('Data linkage partly successful',
   'The linking of data from the cashbook was successful for the following raw files:\n\n{successlisttext}!\n\n\n\n The matching failed for the following raw files:\n\n{errorlisttext}'),
  'classtableimport_notexist': ('Classification table not found',
   'Please select the folder where the classification table is located'),
  'classtableimport_succ': ('Classification table successfully set', ''),
  'classtableimport_err': ('Import error',
   'No classification table was found in the selected folder.'),
  'excludelist': ('roundies', 'cashbook')},
 'Classifier_vars':{'tablename': ('Classification_Table.xlsx', 'Category'),
  'tablesheets': ('Current_Account', 'Credit_Card'),
  'noncategory': ('other', '')},
 'Data_Proc_vars': {'act_value': ('credit card', ''),
  'sheetname_rawdata': ('raw data', ''),
  'cashbookvars_name': ('cashbook', 'cash payment'),
  'holidayvars_name': ('vacations', 'vacations_results'),
  'holiday_searchwords':('vacation|vacations|holiday|holidays|leave|journey',''),
  'dataname_savecent': ('roundies', ''),
  'result_pathvars': ('Results_', '_evaluated'),
  'balance_normal': ('Total balance\nin period', ''),
  'balance_savecent': ('Total roundies', ''),
  'balance_cashbook': ('Sum of cash payments taken into account',
   'Total sum of\ncash payments'),
  'sheetname_basis': ('Processed Data', ["booking date","valuta date","act","transction info","value ("+self.currency_var+")","month","category"]),
  'sheetname_catdata': ('Listing by categories', ["category","total sum ("+self.currency_var+")","average value per month ("+self.currency_var+")"]),
  'sheetnames_savecent1': ('Processed Data', ["booking date","valuata date","act","transaction info","value ("+self.currency_var+")","month","category","roundies","roundies origin"]),
  'sheetnames_savecent2': ('Roundies by month', ["month","Roundies ("+self.currency_var+")"]),
  'sheetnames_savecent3': ('Roundies by origin',["origin of roundies","Total roundies ("+self.currency_var+")","average value per month ("+self.currency_var+")"]),
  'sheetnames_cashbook1': ('Processed Data', ["booking date","valuata date","act","transction info","value ("+self.currency_var+")","month","category","account","cash category name"]),
  'sheetnames_cashbook2': ('Listing by categories', ["category","total sum ("+self.currency_var+")","average value per month ("+self.currency_var+")"]),
  'sheetnames_cashbook3': ('Listing by cash origin', ["cash origin account name","total sum ("+self.currency_var+")","average value per month ("+self.currency_var+")"])},
 'Plot_Proc_vars': {'costplot_search': ('vacation|total sum|other|withdrawal|cash',
   '',
   '',
   ''),
  'costplot_savecent': ('roundies',
   'Overview of origin and sum of "{element_name}"',
   'Overview roundies.png',
   ''),
  'monthplot_savecent': ('roundies',
   'Descending order of "{element_name}" per month',
   'Monthly roundies.png',
   ''),
  'costplot_holiday_rename': ('vacations',
   'Total balance\nin period',
   'total expenses\nvacation',
   ''),
  'costplot_holiday': ('vacations',
   'List of costs per vacation',
   'Vacations overview.png',
   ''),
  'monthplot_holiday': ('vacations',
   'Monthly list of vacation expenses',
   'Vacations monthly overview.png',
   ''),
  'costplot_cashbook1': ('cashbook',
   'Overview of cash payments by cost categories',
   'Cash payments overview.png',
   ''),
  'costplot_cashbook2': ('cashbook',
   'Overview of cash payments by account',
   'Cash withdrawal overview.png',
   ''),
  'monthplot_cashbook': ('cashbook',
   'Monthly list of cash payments',
   'Cash payments monthly overview.png',
   ''),
  'costplot_basis': ('Total balance\nin period',
   'Detailed overview of the cost categories for "{element_name}"',
   'Overview cost categories.png',
   ''),
  'monthplot_basis': ('Total balance\nin period',
   'List of monthly balances for "{element_name}".',
   'monthly cost overview.png',
   ''),
  'overviewplot_adjustments1': ('rent',
   'Total balance\nin period',
   'Share transactions',
   'ETF / investment saving'),
  'overviewplot_adjustments2': ('income incl.\nInvestment balance',
   'remaining costs',
   '',
   ''),
  'overviewplot_plotinfo': ('Income and cost overview for "{element_name}"',
   'Income und TOP-costs',
   'Income incl. capital investments‘ balance\n & remaining costs',
   'Total Overview.png'),
  'piechart_2%name': ('remaining stakes <2.5%', '', '', ''),
  'holiday_adjust_words': ('vacation',
   'vacations ',
   'roundies',
   'cashbook'),
  'holiday_adjust_costplot': ('all vacations',
   'Overview of all cost categories (vacations in total) for "{element_name}"',
   'Overview cost categories_vacations together.png',
   ''),
  'holiday_adjust_piechart': ('Pie chart showing cost stakes >2.5% for "{element_name}"',
   'Overview of stakes with vacations as sum',
   'Overview of stakes without vacations',
   'Pie chart costs_vacation focus.png'),
  'invest_adjust_words': ('Share transactions',
   'ETF / investment saving',
   '',
   ''),
  'invest_adjust_costplot': ('overview of all cost categories (vacations in total',
   ' no investment costs) for "{element_name}"',
   'Overview cost categories_no investcosts.png',
   ''),
  'invest_adjust_piechart': ('Pie chart showing cost stakes >2.5% for "{element_name}"',
   'Overview of stakes with investment costs',
   'Overview of stakes without investment costs',
   'Pie chart costs_invest focus.png'),
  'income_adjust_words1': ('vacations', 'roundies', 'cashbook', ''),
  'income_adjust_words2': ('salary', 'wage', '', ''),
  'income_costplot': ('overview of all income sources for "{element_name}"',
   'Income overview.png'
   ,
   '',
   ''),
  'income_piechart': ('Pie chart showing income stakes >2.5% for "{element_name}"',
   'Overview of iincome stakes with wage/salaries',
   'Overview of iincome stakes without wage/salaries',
   'Pie chart income.png'),
  'boxsplit_partname': (' part ', '', '', ''),
  'boxplot_info': ('Boxplot of all transactions sorted by category for "{element_name}"',
   'Boxplot.png',
   '',
   ''),
  'vioplot_info': ('Violinplot of all transactions sorted by category for "{element_name}"',
   'Violinplot.png',
   '',
   '')},
  'Plotting_vars': {'axcatdata': ('category', ''),
   'timesep_month': ('till', ''),
   'box_violplot_xaxis': ('transactions ('+self.currency_var+')', ''),
   'costplot_yaxes': ('Total value ('+self.currency_var+')', 'Average monthly value ('+self.currency_var+')'),
   'monthplot_extralabel': ('Ø-monthly balance\n in total period:\n', ''),
   'monthplot_axes': ('months', 'Balance per month')}}



#-----------------------------------------Plotting Dictionary Function-----------------------




def langdict_printer(filepath,lang_value):

    script_list_sheets=['Main_File','GUI_Final','Main_Func','Data_Proc','Plot_Proc','Plotting']#sheetnames in lang excel

    langname='self.lang_'+lang_value+" = "

    lang_dict={}

    for entry in script_list_sheets:    
        scriptdict_name=entry+'_vars'
        scriptdict={}
        raw_data=pd.read_excel(filepath,engine='openpyxl',sheet_name=entry,index_col=0)['Value_'+lang_value]
	        
        for num in range(len(raw_data)):
            if entry=='Plot_Proc':
                val=(raw_data[num].split(',')[0],raw_data[num].split(',')[1],raw_data[num].split(',')[2],raw_data[num].split(',')[3])
            else:
                val=(raw_data[num].split(',')[0],raw_data[num].split(',')[1])
            scriptdict[raw_data.index[num]]=val
        
        lang_dict[scriptdict_name]=scriptdict

    print('\n\n'+langname)
    print(lang_dict)




##import excel values and print, if script ist executed as main
if __name__ == "__main__":
    print('Willkommen zur Wörterbuch-Einlesefunktion!')
    folder_raw=input('Bitte geben Sie den genauen Ordnerpfad an, in dem sich die Exceldatei mit den Sprachvariablen befindet.\n')+'/'
    filename=input('\nBitte geben Sie den Namen der Exceldatei ein.\n')
    lang_value=input('\nBitte geben Sie die gewünschte Sprache ein (deu/eng)\n')

    langdict_printer(folder_raw+filename,lang_value)

