'''Language Dictionaries'''

import pandas as pd

 ##
class LanguageDictionary:

    def __init__(self, currency_choice):

        self.currency_choice = currency_choice
#-----------------------------------------German Dictionary-----------------------


        self.lang_deu = {'Main_File_vars': {'data_prep_succ': ('Datenaufbereitung abgeschlossen',
                                                               'Die Daten werden nun visualisiert. Bitte haben Sie einen Moment Geduld!'),
                                            'data_prep_err7': ('Datenaufbereitung abgebrochen',
                                                               'Der Excelexport konnte nicht abgeschlossen werden (Err07). Das Programm wird geschlossen.'),
                                            'data_vis_succ': ('Datenvisualisierung erfolgreich abgeschlossen',
                                                              'Die Ergebnisse wurden unter folgendem Ordner abgelegt:\n\n{self.master.mfunc.accounts_data.dir_result}\n\nWenn Sie csv-Daten eingelesen haben, überprüfen Sie bitte die vorgeschlagenen Kategorien in der Ergebnis-Excel und lesen die korrigierte Datei erneut ein!\n\nDas Programm wird jetzt geschlossen.'),
                                            'data_vis_err8': ('Datenvisualisierung abgebrochen',
                                                              'Die Diagrammvorverarbeitung konnte nicht abgeschlossen werden (Err08). Das Programm wird jetzt geschlossen.'),
                                            'data_vis_err9': ('Datenvisualisierung abgebrochen',
                                                              'Diagramme konnten nicht erstellt werden (Err09). Das Programm wird jetzt geschlossen.')},
                         'GUI_Final_vars': {'mainwin_choice1': ('Csv-Daten analysieren', ''),
                                            'mainwin_choice2': ('Excel-Daten analysieren', ''),
                                            'mainwin_choice3': ('Urlaube separat auswerten', ''),
                                            'mainwin_choice4': ('Sparcents ausgeben', ''),
                                            'mainwin_choice5': ('Daten zusammenfügen', ''),
                                            'mainwin_choice6': ('Haushaltsbuch mit Bargeldzahlungen in die Datenanalyse einbeziehen', ''),
                                            'mainwin_choice7': ('Gespeicherte Langzeitdaten der Konten auswerten und ausgeben', ''),
                                            'mainwin_choice8': ('Csv-Daten mit bestehenden Excel-Dateien verknüpfen', ''),
                                            'mainwin_separator_text': ('<big>Weitere Analyse-Optionen</big>', ''),
                                            'mainwin_btn1': ('Rohdaten auswählen', ''),
                                            'mainwin_btn2': ('Auswertung starten', ''),
                                            'mainwin_xlsxinfo': ('Bitte beachten',
                                                                 'Excel-Dateien, die ausgewertet werden sollen, müssen ein Tabellenblatt "Aufbereitete Daten" in der KYSA-eigenen Formatierung aufweisen. Wenn Sie bisher keine Daten ausgewertet haben, wählen Sie bitte "csv-Daten analysieren"!'),
                                            'mainwin_donatinfo': ('Gefällt Ihnen KYSA?',
                                                                  'KYSA ist als Open-Source-Projekt auf Ihre Unterstützung angewiesen. Für weitere Informationen drücken Sie bitte OK. Vielen Dank!'),
                                            'aboutwin_link': ('http://www.digital-souveraenitaet.de/kysa-', 'KYSA Webseite'),
                                            'aboutwin_title': ('Über KYSA', ''),
                                            'donatewin_header': ('Unterstützen', ''),
                                            'donatewin_title': ('<big>Spenden für KYSA</big>', ''),
                                            'donatewin_text': ('KYSA ist ein Open-Source-Projekt und soll es auch bleiben.\nAuch wenn es nicht so wirkt, ist auch die Entwicklung einer kleinen Software sehr zeitaufwändig  und trotz der Verwendung von anderen Open-Source-Programmbibliotheken dennoch mit Kosten verbunden.\n\nWenn Ihnen KYSA gefällt und hilft, unterstützen Sie mich gerne mit einer kleinen Spende.  Ich freue mich auch über kleine Spenden, um dieses Programmprojekt weiter zu verbessern.  Als Dienstleister für Spenden (auch für meinen Blog) nutze ich die Open-Source-Spendenplattform Liberapay.  Alles weitere zum Spendenprozess findet sich auf der verlinkten Webseite: ', ''),
                                            'donatewin_link': ('https://de.liberapay.com/Waldbader/donate', 'Spenden über Liberapay'),
                                            'setuiwin_header': ('Einstellungen Benutzeroberfläche', ''),
                                            'setuiwin_title': ('<big>Einstellungen für Benutzeroberfläche</big>', ''),
                                            'setuiwin_choicelabel': ('<b>Anzeigesprache</b>', '<b>Währungssymbol</b>'),
                                            'setuiwin_currencies1': ('Euro (€)', 'Dollar ($)'),
                                            'setuiwin_currencies2': ('Pfund (£)', 'Krone (Kr)'),
                                            'setuiwin_btn': ('Einstellungen speichern', ''),
                                            'setuiwin_nochoice':('Keine Änderungen vorgenommen', 'Sie können die Datenanalyse mit den bestätigten Voreinstellungen ohne Programmneustart beginnen.'),
                                            'setuiwin_newchoice' : ('Bitte beachten:', 'Die gewählten Einstellungen werden erst mit einem Programmneustart wirksam. Klicken Sie "OK" um das Programm jetzt zu schließen.'),
                                            'accsettingswin_header': ('Konten verwalten', 'Konten für Daten-Zuordnung definieren'),
                                            'accsettingswin_descrlabel': ('Existierende\nKonten:', ''),
                                            'accsettingswin_closebtn': ('Schließen', ''),
                                            'setaccnamewin_header': ('Kontonamen eingeben', ''),
                                            'setaccnamewin_entrylabel': ('Geben Sie einen Namen für das neue Konto ein:', 'Geben Sie einen Namen für das zu ändernde Konto ein:'),
                                            'setaccnamewin_errnoname': ('Fehlerhafte Eingabe', 'Sie haben keinen Namen eingegeben'),
                                            'setaccnamewin_errname': ('Fehlerhafte Eingabe', 'Sie haben einen bereits vergebenen Kontoamen eingegeben'),
                                            'fileacclinkwin_header': ('Kontenzuordnung', ''),
                                            'fileacclinkwin_proceed': ('Fortfahren', ''),
                                            'fileacclinkwin_collabels': ('Konten', 'Importierte Dateien:'),
                                            'fileacclinkwin_nochoice': ('nicht zugeordnet', ''),
                                            'concatwin_header':('Daten-Zusammenführung', ''),
                                            'concatwin_btn1': ('Abbrechen', ''),
                                            'concatwin_btn2': ('Weiter', ''),
                                            'concatwin_entryname': ('Name für Datei {(colid+1)}:', ''),
                                            'concatwin_choicename': ('Datei {colid+1}', ''),
                                            'concatwin_errselect': ('Unvollständige Eingabe',
                                                                    'Bitte wählen Sie mindestens 2 Dateien aus\noder brechen diesen Schritt ab!'),
                                            'concatwin_errnoname': ('Unvollständige Eingabe',
                                                                    'Sie haben für Ihre Auswahl keinen Namen eingegeben!'),
                                            'concatwin_errname': ('Fehlerhafte Eingabe',
                                                                  'Sie haben einen Namen eingegeben'),
                                            'concatwin_succ': ('Erfolgreiche Verknüpfungsauwahl!', ''),
                                            'prgrsswin_header': ('Datenverarbeitung läuft', ''),
                                            'prgrsswin_visualinfo': ('Datenvisualisierung läuft', '')},
                         'Main_Func_vars': {'filechooser_csv': ('Csv-Dateien auswählen', ''),
                                            'filechooser_xlsx': ('Excel-Dateien auswählen', ''),
                                            'filechooser_longterm': ('Excel-Dateien für Verknüfung mit csv-Dateien auswählen', ''),
                                            'filechooser_cashbook': ('Haushaltsbuch-Excel-Datei auswählen', ''),
                                            'filechooser_classdir': ('Ordner mit Zuordnungstabelle auswählen', ''),
                                            'filechooser_resdir': ('Ablageordner für Ergebnisse auswählen', ''),
                                            'filechooser_filter1': ('CSV Dateien', ''),
                                            'filechooser_filter2': ('Excel Dateien', ''),
                                            'filechooser_filter3': ('Alle Dateien', ''),
                                            'start_analysis_info': ('Rohdaten Import',
                                                                    'KYSA versucht nun, die ausgewählten Rohdaten zu importieren und den Umsätzen Kategorien zuzuweisen. Bitte haben Sie einen Augenblick Geduld!'),
                                            'start_analysis_err1': ('Fehlende Rohdaten',
                                                                    'Bitte wählen Sie mindestens eine Rohdatei oder markieren das Kästchen für die Auswertung von Langzeit-Daten!'),
                                            'start_analysis_err2': ('Unplausible Auswahl',
                                                                    'Es wurde nur eine Datei eingegeben, aber die Daten-Zusammenführung gewählt.'),
                                            'importcheck_err': ('Fehler beim Datenimport!',
                                                                'Es konnte keine der ausgewählten Dateien verarbeitet werden!\n\nWählen Sie neue Dateien!\n\nFehlercode(s):\n\n({errorcodes})'),
                                            'importcheck_succall': ('Datenimport abgeschlossen!',
                                                                    'Alle Dateien wurden erfolgreich importiert!'),
                                            'importcheck_succpart': ('Datenimport abgeschlossen!',
                                                                     'Es wurde:\n\n{successlisttext}\n\nerfolgreich eingelesen.\n\n\nFolgende Dateien konnten nicht verarbeitet werden:\n\n{errorlisttext}'),
                                            'extraimport_longterm': ('Zusätzliche Excel-Dateien einlesen',
                                                                     'Bitte wählen Sie im folgenden Schritt die Excel-Dateien für die Zusammenführung mit den csv-Daten aus oder brechen ab.'),
                                            'extraimport_cashbook': ('Haushaltsbuch einlesen',
                                                                     'Bitte wählen Sie im folgenden Schritt die Excel-Datei mit den Bargeldzahlungen aus oder brechen ab.'),
                                            'cashbookinfo_nodata': ('Keine Verknüpfung erfolgt',
                                                                    'Es wurden für die importierten Rohdaten keine korrespondierenden Daten im Haushaltsbuch gefunden.'),
                                            'cashbookinfo_err': ('Verknüpfung fehlgeschlagen',
                                                                 'Es konnten keine Daten aus dem Haushaltsbuch verknüpft werden.\nFolgende Codes weisen auf die Gründe hin:\n\n{errorlisttext}'),
                                            'cashbookinfo_succ': ('Verknüpfung erfolgreich!',
                                                                  'Zu folgenden importierten Rohdateien konnten passende Daten aus dem Haushaltsbuch hinzugefügt werden:\n\n{successlisttext}'),
                                            'cashbookinfo_succpart': ('Verknüpfung teilweise erfolgreich!',
                                                                      'Die Verknüpfung von Daten aus dem Haushaltsbuch war für folgende Rohdateien erfolgreich:\n\n{successlisttext}!\n\n\nBei folgende Rohdateien schlug der Abgleich fehl:\n\n{errorlisttext}'),
                                            'classtableimport_notexist': ('Zuordnungstabelle nicht gefunden!',
                                                                          'Wählen Sie den neuen Ordner'),
                                            'classtableimport_succ': ('Zuordnungstabelle erfolgreich gespeichert!', ''),
                                            'classtableimport_err': ('Fehler beim Import',
                                                                     'Im gewählten Ordner wurde keine Zuordnungstabelle gefunden.'),
                                            'excludelist': ('Sparcents', 'Haushaltsbuch'),
                                            'data_prep_start': ('Datenaufbereitung beginnt',
                                                                'Die Rohdaten werden nun entsprechend Ihrer Auswahl weiterverarbeitet und für die Diagramme aufbereitet.')},
                         'Classifier_vars':{'tablename': ('Zuordnungstabelle.xlsx', ''),
                                            'tablesheets': ('Suchwörter', 'Hauptkategorien'),
                                            'noncategory': ('Unklar', 'Unbekannte\nKategorien'),
                                            'acctransfer': ('Kreditkarten-\nübertrag', 'Sonstige\nEinnahmen')},
                         'Data_Proc_vars': {'act_value': ('Kreditkartentransaktion', ''),
                                            'sheetname_rawdata': ('Rohdaten', ''),
                                            'accname_labels': ('Kontozuordnung', 'nicht zugeordnet'),
                                            'longterm_name': ('Langzeit_', ''),
                                            'cashbookvars_name': ('Haushaltsbuch', 'Bargeldzahlung'),
                                            'holidayvars_name': ('Urlaube', 'Urlaubsauswertung'),
                                            'holiday_searchwords':('Urlaub &\nReisen', ''),
                                            'dataname_savecent': ('Sparcents', ''),
                                            'result_pathvars': ('Ergebnisse_', '_Auswertung'),
                                            'balance_normal': ('Gesamtsaldo\nder Periode', ''),
                                            'balance_holiday': ('Summe aller\nUrlaubsausgaben', ''),
                                            'balance_savecent': ('Gesamtsumme der\nSparcents', ''),
                                            'balance_cashbook': ('Summe der berücksichtigten Haushaltsbuchkosten in der Periode', 'Gesamtsumme der\nBargeldzahlungen'),
                                            'sheetname_basis': ('Aufbereitete Daten', ["Buchungstag", "Wertstellung (Valuta)", "Vorgang", "Buchungsinformationen", "Umsatzbetrag ("+self.currency_choice+")", "Monat", "Kategorie", "Hauptkategorie", "Kontozuordnung"]),
                                            'sheetname_maincatdata': ('Aufstellung Hauptkategorien', ["Hauptkategorie", "Kumulierte Absolutbeträge ("+self.currency_choice+")", "Durchschnittliche Absolutbeträge pro Monat ("+self.currency_choice+")"]),
                                            'sheetname_catdata': ('Aufstellung Kategorien', ["Hauptkategorie", "Kategorie", "Kumulierte Absolutbeträge ("+self.currency_choice+")", "Durchschnittliche Absolutbeträge pro Monat ("+self.currency_choice+")"]),
                                            'sheetname_holidaycatdata': ('Aufstellung Kategorien', ["Kategorie", "Kumulierte Absolutbeträge ("+self.currency_choice+")", "Durchschnittliche Absolutbeträge pro Monat ("+self.currency_choice+")"]),
                                            'sheetnames_savecent1': ('Aufbereitete Daten', ["Buchungstag", "Wertstellung (Valuta)", "Vorgang", "Buchungsinformationen", "Umsatzbetrag ("+self.currency_choice+")", "Monat", "Kategorie", "Hauptkategorie", "Sparcents ("+self.currency_choice+")", "Herkunft Sparcent"]),
                                            'sheetnames_savecent2': ('Monatliche Sparcents', ["Monat", "Sparcents ("+self.currency_choice+")"]),
                                            'sheetnames_savecent3': ('Sparcents nach Konto-Herkunft', ["Herkunft Sparcent", "Kumulierte Sparcents ("+self.currency_choice+")", "Durchschnittliche Sparcents pro Monat ("+self.currency_choice+")"]),
                                            'sheetnames_cashbook1': ('Aufbereitete Daten', ["Buchungstag", "Wertstellung (Valuta)", "Vorgang", "Buchungsinformationen", "Umsatzbetrag ("+self.currency_choice+")", "Monat", "Kategorie", "Hauptkategorie", "Konto", "Bargeldbezeichnung"]),
                                            'sheetnames_cashbook2': ('Aufstellung Kategorien', ["Kategorie", "Kumulierte Absolutbeträge ("+self.currency_choice+")", "Durchschnittliche Absolutbeträge pro Monat ("+self.currency_choice+")"]),
                                            'sheetnames_cashbook3': ('Aufstellung Bargeldherkunft', ["Bargeldherkunft Kontoname", "Kumulierte Absolutbeträge ("+self.currency_choice+")", "Durchschnittliche Absolutbeträge pro Monat ("+self.currency_choice+")"])},
                         'Plot_Proc_vars': {'costplot_search': ('Urlaub|Gesamtsaldo|Bargeldzahlung',
                                                                '', '', ''),
                                            'costplot_savecent': ('Sparcents', 'Übersicht über die Herkunft und Summe der "{element_name}"',
                                                                  'Übersicht Sparcents.png', ''),
                                            'monthplot_savecent': ('Sparcents', 'Absteigend sortierte Aufstellung der "{element_name}" je Monat',
                                                                   'Monatliche Sparcents.png', ''),
                                            'costplot_holiday': ('Urlaube', 'Kostensummen der einzelnen Urlaube',
                                                                 'Übersicht Urlaubskosten.png', ''),
                                            'monthplot_holiday': ('Urlaube', 'Monatliche Aufstellung der Urlaubsausgaben',
                                                                  'Monatsaufstellung Urlaube.png', ''),
                                            'costplot_cashbook1': ('Haushaltsbuch', 'Übersicht über die Bargeldzahlungen nach Kostenkategorien',
                                                                   'Kategorieübersicht Bargeldzahlungen.png', ''),
                                            'costplot_cashbook2': ('Haushaltsbuch', 'Übersicht über die erfassten Bargeldzahlungen nach Konto',
                                                                   'Kontoübersicht Bargeldzahlungen.png', ''),
                                            'monthplot_cashbook': ('Haushaltsbuch', 'Monatliche Aufstellung der Bargeldzahlungen',
                                                                   'Monatsaufstellung Bargeldzahlungen.png', ''),
                                            'costplot_basis_subcats': ('Gesamtsaldo\nder Periode', 'Detaillierte Gesamtübersicht der Kostenkategorien für "{element_name}"',
                                                                       'Komplettübersicht Einzelkostenkategorien.png', ''),
                                            'costplot_basis_maincats': ('Gesamtsaldo\nder Periode',
                                                                        'Gesamtübersicht Hauptkostenkategorien für "{element_name}"',
                                                                        'Übersicht Hauptkostenkategorien.png',
                                                                        ''),
                                            'monthplot_basis': ('Gesamtsaldo\nder Periode', 'Aufstellung der Monatssalden für "{element_name}"',
                                                                'Monatsaufstellung.png', ''),
                                            'overviewplot_searchwords': ('Wohnen & gr.\nAnschaffungen', 'Gesamtsaldo\nder Periode',
                                                                         'Investments &\nAltersvorsorge', ''),
                                            'overviewplot_newnames': ('Einkünfte inkl.\nInvestergebnis',
                                                                      'Restliche Kosten-\npositionen',
                                                                      '', ''),
                                            'overviewplot_plotinfo': ('Überblick Hauptkosten und Einkünfte für "{element_name}',
                                                                      'Einnahmequellen (max. 3) und TOP3-Hauptkosten',
                                                                      'Einkünfte inkl. Saldo Kapitalanlagen vs.\nKosten für Wohnen & Rest',
                                                                      'TOP-Übersicht.png'),
                                            'piechart_2%name': ('Restliche mit <2,5%', '', '', ''),
                                            'cost_piechart_adjust': ('Urlaub &\nReisen', 'Vorgeschlagene\nKategorien', '', ''),
                                            'costs_piechart_main':('Tortendiagramm Hauptkosten mit Aufgliederung TOP3 (ohne Urlaub) für "{element_name}"', 'Tortendiagramm Hauptkostenbereiche.png',
                                                                   '', ''),
                                            'costs_piechart_sub': ('Anteilsübersicht Hauptkostenkategorien', 'Aufgliederung für "{top3_maincatname}"',
                                                                   'Aufgliederung für "{top3_maincatname}"', 'Aufgliederung für "{top3_maincatname}"'),
                                            'revenues_adjust_words1': ('Lohn|Gehalt|'),
                                            'revenues_costplot': ('Detaillierte Übersicht über die verschiedenen Einkommensquellen für "{element_name}"',
                                                                  'Einkommensübersicht.png',
                                                                  '', ''),
                                            'revenues_piechart_main': ('Tortendiagramm Einkommensquellen >2,5% Anteil für "{element_name}"',
                                                                       'Tortendiagramm Einkommensquellen.png',
                                                                       '', ''),
                                            'revenues_piechart_sub': ('Anteilsübersicht mit Lohn / Gehalt',
                                                                      'Anteilsübersicht ohne Lohn / Gehalt',
                                                                      '', ''),
                                            'boxsplit_partname': (' Teil ', '', '', ''),
                                            'boxplot_info': ('Boxplot aller Umsätze nach Kategorie für "{element_name}"',
                                                             'Boxplot.png', '', ''),
                                            'vioplot_info': ('Violinplot aller Umsätze nach Kategorie für "{element_name}"',
                                                             'Violinplot.png',
                                                             '', '')},
                         'Plotting_vars': {'ax_catlabel': ('Kategorie', ''),
                                           'separator_months': ('bis', ''),
                                           'box_violplot_xaxis': ('Einzelumsätze ('+self.currency_choice+')', ''),
                                           'costplot_yaxes': ('Gesamtbeträge der Periode ('+self.currency_choice+')', 'Durschschnittliche Monatsbeträge ('+self.currency_choice+')'),
                                           'overviewplot_extralabel':('Einnahmen', 'Hauptkosten'),
                                           'monthplot_extralabel': ('Ø-Monatssaldo des\n Gesamtzeitraums:\n', ''),
                                           'monthplot_axes': ('Saldo je Monat ('+self.currency_choice+')', 'Monate'),
                                           'pieplot_wordsexcl':('Urlaub &\nReisen', 'Vorgeschlagene\nKategorien'),
                                           'pieplot_maincosts': ('Anteilsübersicht Hauptkostenkategorien', '')}}



#-----------------------------------------English Dictionary-----------------------

        self.lang_eng = {'Main_File_vars': {'data_prep_succ': ('Data processing successful',
                                                               'The data is now visualized. Please wait a moment!'),
                                            'data_prep_err7': ('Data processing interrupted',
                                                               'The Excelexport could not be completed (Err07). The program is closed.'),
                                            'data_vis_succ': ('Data visualization successful',
                                                              'The results have been saved to the following folder:\n\n{self.master.mfunc.accounts_data.dir_result}\n\nIf you analyzed csv data, please check the suggested categories in the evaluated excel and reevaluate the corrected excel file again!\n\nThe program is now closed.'),
                                            'data_vis_err8': ('Data visualization interrupted',
                                                              'The plotting preprocessing could not be completed (Err08). The program is now closed.'),
                                            'data_vis_err9': ('Data visualization interrupted',
                                                              'Diagrams could not be created (Err09). The program is now closed.')},
                         'GUI_Final_vars': {'mainwin_choice1': ('Analyse csv data', ''),
                                            'mainwin_choice2': ('Analyse Excel data', ''),
                                            'mainwin_choice3': ('Extract vacations to separate file', ''),
                                            'mainwin_choice4': ('Calculate Roundies', ''),
                                            'mainwin_choice5': ('Merge data', ''),
                                            'mainwin_choice6': ('Use cashbook entries for analysis', ''),
                                            'mainwin_choice7': ('Evaluate and output stored long-term data', ''),
                                            'mainwin_choice8': ('Link csv data with existing Excel-results', ''),
                                            'mainwin_separator_text': ('<big>Additional options</big>', ''),
                                            'mainwin_btn1': ('Select raw data', ''),
                                            'mainwin_btn2': ('Run analysis', ''),
                                            'mainwin_xlsxinfo': ('Please note',
                                                                 "Excel files that are to be evaluated must have a 'Processed Data' worksheet in KYSA's own formatting. If you have not yet evaluated any data"),
                                            'mainwin_donatinfo': ('Do you like KYSA?', 'KYSA needs your help'),
                                            'aboutwin_link': ('http://www.digital-souveraenitaet.de/kysa-know-your-spendings-eng', 'KYSA website'),
                                            'aboutwin_title': ('About KYSA', ''),
                                            'donatewin_header': ('Support KYSA', ''),
                                            'donatewin_title': ('<big>Donate for KYSA</big>', ''),
                                            'donatewin_text': ("KYSA is an open source project and should remain so.\nEven if it doesn't seem like it, developing a small piece of software is very time-consuming and, despite the use of other open source program libraries, still involves costs.\n\n If you like KYSA and would like to help, please support me with a small donation. Even small amounts help me to further improve this programming project. I use the open source donation platform Liberapay as service provider. Everything else about the donation process can be found on the linked website:",
                                                               ''),
                                            'donatewin_link': ('https://en.liberapay.com/Waldbader/donate', 'Donate via Liberapay'),
                                            'setuiwin_header': ('UI Settings', ''),
                                            'setuiwin_title': ('<big>Set User Interface (UI) preferences</big>', ''),
                                            'setuiwin_choicelabel':('<b>UI language</b>', '<b>Currency sign</b>'),
                                            'setuiwin_currencies1':('Euro (€)', 'Dollar ($)'),
                                            'setuiwin_currencies2':('Pound (£)', 'Krone (Kr)'),
                                            'setuiwin_btn':('Save settings', ''),
                                            'setuiwin_nochoice':('No changes made', 'You can start the data analysis with the preselected preferences without restarting the program.'),
                                            'setuiwin_newchoice':('Please note:', 'Your selection will only become effective after a program restart. Press "OK" to close the program now.'),
                                            'accsettingswin_header': ('Manage accounts', 'Set accounts for data assignment'),
                                            'accsettingswin_descrlabel': ('Existing accounts', ''),
                                            'accsettingswin_closebtn': ('Close', ''),
                                            'setaccnamewin_header': ('Set account name', ''),
                                            'setaccnamewin_entrylabel': ('Enter a name for the new account:', 'Enter a name for the account you want to change:'),
                                            'setaccnamewin_errnoname': ('Incomplete input', 'You have not entered a name for your selection!'),
                                            'setaccnamewin_errname': ('Incorrect input', 'You have entered a name that is already taken!'),
                                            'fileacclinkwin_header': ('Accounts assignment', ''),
                                            'fileacclinkwin_proceed': ('Proceed', ''),
                                            'fileacclinkwin_collabels': ('Accounts', 'Imported files:'),
                                            'fileacclinkwin_nochoice': ('not assigned', ''),
                                            'concatwin_header': ('Concat data', ''),
                                            'concatwin_btn1': ('Cancel', ''),
                                            'concatwin_btn2': ('Proceed', ''),
                                            'concatwin_entryname': ('File name {(colid+1)}:', ''),
                                            'concatwin_choicename': ('File {colid+1}', ''),
                                            'concatwin_errselect': ('Incomplete input',
                                                                    'Please choose at least 2 files\nor skip this step'),
                                            'concatwin_errnoname': ('Incomplete input',
                                                                    'You have not entered a name for your selection!'),
                                            'concatwin_errname': ('Incorrect input',
                                                                  'You have entered a name that is already taken!'),
                                            'concatwin_succ': ('Concatenation successful', ''),
                                            'prgrsswin_header': ('Processing Data', ''),
                                            'prgrsswin_visualinfo': ('Visualizing Data', '')},
                         'Main_Func_vars': {'filechooser_csv': ('Choose csv files', ''),
                                            'filechooser_xlsx': ('Choose excel files', ''),
                                            'filechooser_longterm': ('Choose excel files for concatenation with csv files',
                                                                     ''),
                                            'filechooser_cashbook': ('Choose your cashbook', ''),
                                            'filechooser_classdir': ('Set folder holding classification table', ''),
                                            'filechooser_resdir': ('Set folder for results', ''),
                                            'filechooser_filter1': ('csv files', ''),
                                            'filechooser_filter2': ('excel files', ''),
                                            'filechooser_filter3': ('all files', ''),
                                            'start_analysis_info': ('Import raw data',
                                                                    'KYSA will now try to import the selected raw data and assign categories to the transactions. Please wait a moment!'),
                                            'start_analysis_err1': ('Missing data', 'Please choose at least one file or check the box for evaluating long-term data'),
                                            'start_analysis_err2': ('Implausible selection', 'You selected data merging but only one file was chosen'),
                                            'importcheck_err': ('Import error',
                                                                'None of the selected files could be processed!\n\nPlease select new files!\n\nerrorcode(s):\n\n({errorcodes})'),
                                            'importcheck_succall': ('Import finished', 'All files were successfully imported'),
                                            'importcheck_succpart': ('Import finished',
                                                                     'The following files were processed successfully:\n\n{successlisttext}\n\n\n\n The following files could not be processed:\n\n{errorlisttext}'),
                                            'extraimport_longterm': ('Import additional Excel files',
                                                                     'Please select the Excel files for merging with the csv data in the following step or cancel.'),
                                            'extraimport_cashbook': ('Import cashbook',
                                                                     'Please select the Excel file with the cash payments in the following step or cancel.'),
                                            'cashbookinfo_nodata': ('No data linkage established',
                                                                    'For the imported raw data no corresponding data were found in the cashbook.'),
                                            'cashbookinfo_err': ('Data linkage error',
                                                                 'No data from the cashbook could be linked. \nThe following codes indicate the reasons:\n\n{errorlisttext}'),
                                            'cashbookinfo_succ': ('Data linkage successful',
                                                                  'To the following imported raw files matching data from the cashbook could be added:\n\n{successlisttext}'),
                                            'cashbookinfo_succpart': ('Data linkage partly successful',
                                                                      'The linking of data from the cashbook was successful for the following raw files:\n\n{successlisttext}!\n\n\n\n The matching failed for the following raw files:\n\n{errorlisttext}'),
                                            'classtableimport_notexist': ('Classification table not found',
                                                                          'Please select the folder where the classification table is located'),
                                            'classtableimport_succ': ('Classification table successfully set', ''),
                                            'classtableimport_err': ('Import error', 'No classification table was found in the selected folder.'),
                                            'excludelist': ('roundies', 'cashbook'),
                                            'data_prep_start': ('Data preparation starts',
                                                                'The raw data is now processed according to your selection and prepared for the diagrams.')},
                         'Classifier_vars':{'tablename': ('Classification_Table.xlsx', ''),
                                            'tablesheets': ('search words', 'main categories'),
                                            'noncategory': ('unclear', 'unknown\ncategories'),
                                            'acctransfer': ('account transfer', 'other income')},
                         'Data_Proc_vars': {'act_value': ('credit card', ''),
                                            'sheetname_rawdata': ('raw data', ''),
                                            'cashbookvars_name': ('cashbook', 'cash payment'),
                                            'accname_labels': ('account assignment', 'not assigned'),
                                            'longterm_name': ('long-term_', ''),
                                            'holidayvars_name': ('vacations', 'vacations_results'),
                                            'holiday_searchwords':('vacations &\ntravel', ''),
                                            'dataname_savecent': ('roundies', ''),
                                            'result_pathvars': ('Results_', '_evaluated'),
                                            'balance_normal': ('total balance\nin period', ''),
                                            'balance_holiday': ('total expenses\nvacation', ''),
                                            'balance_savecent': ('total roundies', ''),
                                            'balance_cashbook': ('sum of cash payments taken into account',
                                                                 'total sum of\ncash payments'),
                                            'sheetname_basis': ('Processed Data', ["booking date", "valuta date", "act", "transction info", "value ("+self.currency_choice+")", "month", "category", "main category", "account assignment"]),
                                            'sheetname_maincatdata': ('Listing by main categories', ["main category", "total sum ("+self.currency_choice+")", "average value per month ("+self.currency_choice+")"]),
                                            'sheetname_catdata': ('Listing by categories', ["main category", "category", "total sum ("+self.currency_choice+")", "average value per month ("+self.currency_choice+")"]),
                                            'sheetname_holidaycatdata': ('Listing by categories', ["category", "total sum ("+self.currency_choice+")", "average value per month ("+self.currency_choice+")"]),
                                            'sheetnames_savecent1': ('Processed Data', ["booking date", "valuata date", "act", "transaction info", "value ("+self.currency_choice+")", "month", "category", "main category", "roundies", "roundies origin"]),
                                            'sheetnames_savecent2': ('Roundies by month', ["month", "Roundies ("+self.currency_choice+")"]),
                                            'sheetnames_savecent3': ('Roundies by origin', ["origin of roundies", "Total roundies ("+self.currency_choice+")", "average value per month ("+self.currency_choice+")"]),
                                            'sheetnames_cashbook1': ('Processed Data', ["booking date", "valuata date", "act", "transction info", "value ("+self.currency_choice+")", "month", "category", "main category", "account", "cash category name"]),
                                            'sheetnames_cashbook2': ('Listing by categories', ["category", "total sum ("+self.currency_choice+")", "average value per month ("+self.currency_choice+")"]),
                                            'sheetnames_cashbook3': ('Listing by cash origin', ["account name cash origin", "total sum ("+self.currency_choice+")", "average value per month ("+self.currency_choice+")"])},
                         'Plot_Proc_vars': {'costplot_search': ('vacations|total|cash payments',
                                                                '',
                                                                '',
                                                                ''),
                                            'costplot_savecent': ('roundies',
                                                                  'Overview of origin and sum of "{element_name}"',
                                                                  'Overview roundies.png',
                                                                  ''),
                                            'monthplot_savecent': ('roundies',
                                                                   'Descending order of "{element_name}" per month',
                                                                   'Monthly roundies.png',
                                                                   ''),
                                            'costplot_holiday': ('vacations',
                                                                 'List of costs per vacation',
                                                                 'Vacations overview.png',
                                                                 ''),
                                            'monthplot_holiday': ('vacations',
                                                                  'Monthly list of vacation expenses',
                                                                  'Vacations monthly overview.png',
                                                                  ''),
                                            'costplot_cashbook1': ('cashbook',
                                                                   'Overview of cash payments by cost categories',
                                                                   'Category overview cash payments.png',
                                                                   ''),
                                            'costplot_cashbook2': ('cashbook',
                                                                   'Overview of cash withdrawals by account',
                                                                   'Cash payments by account.png',
                                                                   ''),
                                            'monthplot_cashbook': ('cashbook',
                                                                   'Monthly list of cash payments',
                                                                   'Cash payments monthly overview.png',
                                                                   ''),
                                            'costplot_basis_subcats': ('Total balance\nin period',
                                                                       'Detailed overview of the cost categories for "{element_name}"',
                                                                       'Overview all cost categories.png',
                                                                       ''),
                                            'costplot_basis_maincats': ('Total balance\nin period',
                                                                        'Overview of main cost categories for "{element_name}"',
                                                                        'Overview main cost categories.png',
                                                                        ''),
                                            'monthplot_basis': ('total balance\nin period',
                                                                'List of monthly balances for "{element_name}".',
                                                                'monthly cost overview.png',
                                                                ''),
                                            'overviewplot_searchwords': ('living & big\npurchases',
                                                                         'Total balance\nin period',
                                                                         'investments &\netirement prov.', ''),
                                            'overviewplot_newnames': ('revenues incl. investment balance',
                                                                      'remaining costs',
                                                                      '',
                                                                      ''),
                                            'overviewplot_plotinfo': ('Income and cost overview for "{element_name}',
                                                                      'Revenue sources (max.3) and TOP-main costs',
                                                                      'Income incl. capital investments‘ balance vs.\nliving & remaining costs',
                                                                      'Total Overview.png'),
                                            'piechart_2%name': ('remaining stakes <2.5%', '', '', ''),
                                            'cost_piechart_adjust': ('vacations &\ntravel', 'category proposed\nby machine', '', ''),
                                            'costs_piechart_main':('Pie chart showing main costs & breakdown TOP3 (w/ vacations) for "{element_name}"', 'Pie chart costs.png',
                                                                   '', ''),
                                            'costs_piechart_sub': ('Overview of main cost stakes', 'Breakdown for "{top3_maincatname}"',
                                                                   'Breakdown for "{top3_maincatname}"', 'Breakdown for "{top3_maincatname}"'),
                                            'revenues_adjust_words1': ('salary|wage', '', ''),
                                            'revenues_costplot': ('overview of all income sources for "{element_name}"',
                                                                  'Income overview.png',
                                                                  '', ''),
                                            'revenues_piechart_main': ('Pie chart showing income sources for "{element_name}"',
                                                                       'Pie chart income.png',
                                                                       '', ''),
                                            'revenues_piechart_sub': ('Overview of income stakes with wage/salaries',
                                                                      'Overview of income stakes without wage/salaries',
                                                                      '', ''),
                                            'boxsplit_partname': (' part ', '', '', ''),
                                            'boxplot_info': ('Boxplot of all transactions sorted by category for "{element_name}"',
                                                             'Boxplot.png', '', ''),
                                            'vioplot_info': ('Violinplot of all transactions sorted by category for "{element_name}"',
                                                             'Violinplot.png', '', '')},
                         'Plotting_vars': {'ax_catlabel': ('category', ''),
                                           'separator_months': ('till', ''),
                                           'box_violplot_xaxis': ('transactions ('+self.currency_choice+')', ''),
                                           'costplot_yaxes': ('Total value ('+self.currency_choice+')', 'Average monthly value ('+self.currency_choice+')'),
                                           'overviewplot_extralabel':('revenues', 'main costs'),
                                           'monthplot_extralabel': ('Ø-monthly balance\n in total period:\n', ''),
                                           'monthplot_axes': ('months', 'Balance per month'),
                                           'pieplot_wordsexcl':('vacations &\ntravel', 'category proposed\nby machine'),
                                           'pieplot_maincosts': ('Overview of main cost stakes', '')}}


#-----------------------------------------Plotting Dictionary Function-----------------------




def langdict_printer(filepath, lang_value):

    script_list_sheets = ['Main_File', 'GUI_Final', 'Main_Func', 'Data_Proc', 'Plot_Proc', 'Plotting']#sheetnames in lang excel

    langname = 'self.lang_'+lang_value+" = "

    lang_dict = {}

    for entry in script_list_sheets:
        scriptdict_name = entry+'_vars'
        scriptdict = {}
        raw_data = pd.read_excel(filepath, engine='xlrd', sheet_name=entry, index_col=0)['Value_'+lang_value]

        for num in range(len(raw_data)):
            if entry == 'Plot_Proc':
                val = (raw_data[num].split(',')[0], raw_data[num].split(',')[1], raw_data[num].split(',')[2], raw_data[num].split(',')[3])
            else:
                val = (raw_data[num].split(',')[0], raw_data[num].split(',')[1])
            scriptdict[raw_data.index[num]] = val

        lang_dict[scriptdict_name] = scriptdict

    print('\n\n'+langname)
    print(lang_dict)




##import excel values and print, if script ist executed as main
if __name__ == "__main__":
    print('Willkommen zur Wörterbuch-Einlesefunktion!')
    RAW_FOLDER = input('Bitte geben Sie den genauen Ordnerpfad an, in dem sich die Exceldatei mit den Sprachvariablen befindet.\n')+'/'
    FILENAME = input('\nBitte geben Sie den Namen der Exceldatei ein.\n')
    LANG_TEST = input('\nBitte geben Sie die gewünschte Sprache ein (deu/eng)\n')

    langdict_printer(RAW_FOLDER+FILENAME, LANG_TEST)
